### ISSUE TITLE
BUG 窗口大小的问题

### ISSUE THREAD

**Issue by juruo888** [class-tools/ScratchOff#1]
Description: 窗口 y 坐标过小，导致图片被压缩

Screenshot (If any):  
![](https://s3.bmp.ovh/imgs/2022/06/07/7c8a73bca3458486.png)

Program Version: `1.0.0`

Operating System Version: `Windows 10`

**Comment by juruo888** [comment]
这个锅我修。

**Comment by HC-Teacher** [comment]
@juruo888 你个傻逼这 bug 不就个数字的问题吗

**Comment by HC-Teacher** [comment]
还有测试的傻逼们，你们这都测试不出来吗？？？
