### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by juruo888** [class-tools/ScratchOff#4]
# **已移动到 [Github Project](https://github.com/class-tools/ScratchOff/projects?type=classic)，这里不再更新。**

**Comment by juruo888** [comment]
对于 α 2 Task 4：已在本地工作区修复。

**Comment by HC-Teacher** [comment]
@juruo888 你他妈有大病啊，README 里面的头像明明还是炸的你就给勾上了，傻逼，滚出 class tools

**Comment by juruo888** [comment]
α 3 Task 3~6 本地已修改。

**Comment by juruo888** [comment]
图标的程序支持部分已经完成，只需要完成图标制作了

**Comment by juruo888** [comment]
α 3 PR 已提交。

#8

**Comment by juruo888** [comment]
1.1.0-beta.1 Task 1 参考资料：<https://blog.csdn.net/GYGuo95/article/details/80060328>
