### ISSUE TITLE
EHC 日志输出

### ISSUE THREAD

**Issue by juruo888** [class-tools/ScratchOff#5]
1.1.0-alpha.2：

- [x] 创建 LOG
- [x] 重命名上一个 LOG
- [x] 图片读取出错 LOG
- [x] 关闭程序 LOG
- [x] 开始游戏 LOG

1.1.0-alpha.3：

- [x] 左键点击 LOG
- [x] 窗口大小 LOG
- [x] 右键点击 LOG
- [x] 图片选择 LOG

**Comment by HC-Teacher** [comment]
傻逼

**Comment by HC-Teacher** [comment]
有大病
